### ISSUE TITLE
Nokogiri compatibility issue with Ruby 2.4 on windows

### ISSUE THREAD

**Issue by nahmad2017** [parasew/instiki#48] opened 2017-06-03 10:29 UTC
Nokogiri version 1.7 is not compatible with Ruby 2.4 on windows. An update to Nokogiri (Nokogiri 1.8.0) was planned to be released but it is not released so far.

**Comment by distler** [comment] 2017-06-03 18:58
So we can track this more effectively, that's [this issue](https://github.com/sparklemotion/nokogiri/issues/1618) on the Nokogiri Issue Tracker.

**Comment by nahmad2017** [comment] 2017-06-05 06:23
nokogiri 1.8.0 is released. I updated the gemfile and bundle install succeeded. Now , when I try to run instiki , I get another error "Couldn't load Eventmachine C Extension"

**Comment by nahmad2017** [comment] 2017-06-06 21:42
I don't know what is Eventmachine C extension and I don't know enough in Ruby to be able to debug this issue. I run windows 8.1 and ruby 2.4.1p11 , gem 2.6.11 . Does it seem that the issue is due to some sort of incompatibility between windows and all the gems with the versions I installed or what  ? I would like to know what this event machine gem does so that I might be able to fix it.

**Comment by distler** [comment] 2017-06-06 23:14
Googling around, the remedy for *that* error seems to be

```
gem uninstall eventmachine
```
followed by
```
bundle install
```

Not sure what you would do  if you have other ruby program which rely on the installed `eventmachine` gem.

**Comment by nahmad2017** [comment] 2017-06-07 06:34
This doesn't seem to work.

**Comment by distler** [comment] 2017-06-07 06:47
As a workaround, does
```
gem 'puma'
```
instead of
```
gem 'thin'
```
in the `Gemfile` fix the problem (IIRC, puma does not rely on eventmachine, whereas thin does)?

**Comment by nahmad2017** [comment] 2017-06-07 07:05
It says can't load redcloth_scan (Missing source file)

**Comment by distler** [comment] 2017-06-07 07:55
Something seems to be pooched in your installation. Extensions installed via `bundle install` don't seem to be found when you actually try to run Instiki.

We can work around each of them, 1-by-1, but eventually, we will either tire of the process or hit a wall.

What's your setup? (What Ruby, etc, ...?) And can you, for instance, install gems manually?

**Comment by distler** [comment] 2018-06-25 16:58
Duplicate of Issue #53.

**Closed by distler** 2018-06-25 16:58 UTC
